name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Instalar JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3️⃣ Compilar y correr tests
      - name: Build with Maven
        run: mvn -B clean install

      # 4️⃣ (Opcional) Ejecutar la app
      - name: Run the app (optional)
        run: mvn spring-boot:run &

